{% set name = "TraceInv" %}
{% set data = load_setup_py_data() %}

package:
    name: "{{ name|lower }}"
    version: "{{ data['version'] }}"

source:
    path: ..

# source:
#   url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"

build:
    number: 0
    script: "{{ PYTHON }} -m pip install . -vv"

requirements:
    host:
        - python {{ python }}
        - setuptools
        - pip
        - pytest-runner
    run:
        - python {{ python }}
        - numpy
        - scipy
        - matplotlib
        - seaborn

test:
    imports:
        - TraceInv
        - TraceInv.ComputeLogDeterminant
        - TraceInv.ComputeTraceOfInverse
        - TraceInv.GenerateMatrix
        - TraceInv.InterpolateTraceOfInverse
    requires:
        - pytest

about:
    home: {{ data['url'] }}
    license: MIT
    license_family: MIT
    license_file: LICENSE.txt
    summary: {{ data['description'] }}
    description: {{ data['description'] }}
    doc_url: https://ameli.github.io/TraceInv/index.html
    dev_url: https://github.com/ameli/TraceInv

extra:
    recipe-maintainers:
        - ameli
